# Generated by Django 3.2.6 on 2021-10-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Standard', 'Standard'), ('Admin', 'Admin')], default='Regular', max_length=15, verbose_name='access'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
